-- Active: 1788435117141@@127.0.0.1@3306@smartcoffee_dml_duda
-- DQL - DATA QUERY LANGUAGE (LINGUEGEM DE CONSULTA DE DADOS)
-- ANTES DE INICIAR
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('ANA FLAVIA', 'ANAF@EMAIL.COM', '1973645425921', 'CAMPINAS', TRUE)

-- EX 1: SELECT SIMPLES OU CONSULTA SIMPLES
-- ESTRUTURA SELECT
-- SELECT COLUNA
-- FROM TABELA;

SELECT *
FROM clientes;
-- CONSULTAR TODAS AS COLUNAS

SELECT NOME, TELEFONE
FROM CLIENTES;
-- CONSULTAR COLUNAS ESPECIFICAS

-- EX 2:AS COMO APELIDO OU NOVO NOME AS COLUNAS
SELECT NOME AS NOME_CLIENTES
FROM CLIENTES;

SELECT EMAIL AS EMAIL_CLIENTES, TELEFONE AS CONTATO_CLIENTE
FROM CLIENTES;

-- EX 3: DISTINCT - ELIMINANDO REPETIÇÕES
SELECT DISTINCT CIDADE
FROM CLIENTES;
-- SEM DISTINCT O RESULTADO IRÁ SE REPETIR MAIS VEZES.
-- COM O DISTINCT O RESULTADO IRÁ APARECER UMA VEZ.

-- EX 4: WHERE - FILTRO POR REGISTROS
-- IREMOS DEFINIR CONDIÇÕES
-- = IGUAL
-- <> OU != DIFERENTE
-- > MAIOR QUE
-- >= MAIOR OU IGUAL
-- < MENOR QUE
-- <= MENOR IGUAL
SELECT NOME, PRECO
FROM produto
WHERE ATIVO = TRUE;
-- CONSULTA STATUS DE CLIENTES SE ESTÁ ATIVO OU INATIVO

SELECT ID_PEDIDO, DATA_PEDIDO, VALOR_TOTAL
FROM pedido
WHERE VALOR_TOTAL >= 25.00

-- EX 5: USO DO AND, OR E NOT
-- AND É PARA TODAS AS CONDIÇÕES VERDADEIRAS
SELECT NOME, PRECO 
FROM produto
WHERE PRECO >= 8.00 AND PRECO <= 25.00

-- OR - PELO MENOS UMA CONDIÇÃO VERDADEIRA
SELECT NOME, CIDADE
FROM clientes
WHERE CIDADE = 'LIMEIRA' OR CIDADE = 'PIRACICABA';

-- NOT - NÃO IRÁ BUSCAR OU CONSULTAR O VALOR DESEJADO
SELECT NOME, CIDADE
FROM clientes
WHERE NOT CIDADE = 'LIMEIRA';

-- EXTRA - UTILIZANDO AND E OR JUNTOS SEPARAR POR ()
SELECT NOME, CIDADE, ATIVO
FROM clientes
WHERE ATIVO = TRUE
AND (CIDADE = 'LIMEIRA' OR CIDADE = 'PIRACICABA');

-- EX 6: BETWEEN - ENTRE DOIS VALORES
-- LIMITE INICIAL E FINAL
SELECT NOME, PRECO 
FROM produto
WHERE PRECO BETWEEN 8.00 AND 15.00;
-- CONSULTA POR VALORES ENTRE 8 E 15

SELECT ID_PEDIDO, DATA_PEDIDO VALOR_TOTAL
FROM pedido
WHERE DATA_PEDIDO BETWEEN '2026-09-01 00:00:00' AND '2026-09-30 23:59:59'
-- CONSULTA POR INTERVALO DE DATAS

-- EX 7: IN VÁRIAS POSSIBILIDADES
SELECT NOME, CIDADE
FROM clientes
WHERE CIDADE IN ('LIMEIRA', 'CAMPINAS', 'AMERICANA', 'PIRACICABA');
-- CONSULTA COM VÁRIAS CONDIÇÕES E DIMINUINDO O USO DE OR

SELECT NOME, CIDADE
FROM clientes
WHERE CIDADE NOT IN ('LIMEIRA', 'PIRACICABA');

-- EX 8: LIKE - PESQUISAR POR TEXTOS
-- CORINGAS
-- % VÁRIOS CARACTERES
-- _ EXATAMENTE UM CARACTER
SELECT NOME 
FROM produto
WHERE NOME LIKE 'CAFÉ%';
-- CONSULTA TODOS OS PRODUTOS QUE COMEÇAM COM A PALAVRA DESEJADA

SELECT NOME   
FROM produto
WHERE NOME LIKE '%CHOCOLATE%';
-- CONSULTA TODOS OS PRODUTOS QUE POSSUAM A PALAVRA DESEJADA

SELECT NOME     
FROM clientes
WHERE NOME LIKE '%SILVA';
-- CONSULTA TODOS OS CLIENTES QUE TERMINAM COM A PALAVRA DESEJADA

SELECT NOME    
FROM CLIENTES 
WHERE NOME LIKE '%SIL_VA';
-- CONSULTA ESPECIFICAMENTE O CARACTER QUE NÃO SE LEMBRA


-- EX 9: NULL - AUSÊNCIA DE VALORES
SELECT NOME, TELEFONE
FROM CLIENTES
WHERE TELEFONE IS NULL;
-- CONSULTA CAMPOS QUE POSSUEM O NULL 


SELECT NOME, TELEFONE
FROM CLIENTES 
WHERE TELEFONE IS NOT NULL;
-- CONSULTA CAMPOS QUE NÃO SÃO MAIS NULL

-- EX 10: ORDER BY - ORDENANDO RESULTADOS
-- ASC CRESCENTE
-- DESC DECRESCENTE
SELECT NOME, PRECO  
FROM produto
ORDER BY PRECO ASC;
-- CONSULTAR DADOS DE FORMA CRESCENTE

SELECT NOME, PRECO  
FROM produto
ORDER BY PRECO DESC;
-- CONSULTAR DADOS DE FORMA DECRESCENTE

SELECT CIDADE, NOME  
FROM clientes
ORDER BY CIDADE ASC, NOME DESC;
-- CONSULTA POR MAIS DE UMA COLUNA

-- EX 11: LIMIT - LIMITAR QUANTIDADE DE LINHAS
SELECT NOME, PRECO 
FROM produto
ORDER BY PRECO DESC
LIMIT 5;
-- CONSULTAR APENAS UMA QUANTIDADE ESPECIFICA DE LINHAS

SELECT NOME, PRECO 
FROM produto
ORDER BY NOME
LIMIT 5 OFFSET 5;
-- CONSULTAR COM LIMITE DE VALORES E LINHAS

-- EX 12: CÁLCULO DE COLUNAS
SELECT NOME, PRECO, PRECO * 1.10 AS PRECO_AJUSTADO
FROM PRODUTO;

SELECT ID_ITEM, QUANTIDADE, PRECO_UNITARIO, QUANTIDADE * PRECO_UNITARIO AS SUB_TOTAL
FROM item_pedido;

-- EX 13: FUNÇÕES PARA CONSULTAS
-- TEXTOS
SELECT UPPER(NOME) AS NOME_CLIENTE, LOWER(EMAIL) AS EMAIL_CLIENTE
FROM CLIENTES;

SELECT CONCAT(NOME, '---', CIDADE) AS CIDADE_CLIENTES
FROM clientes;
-- CONCAT - CONCATENAÇÃO DE VALORES

-- NÚMEROS
SELECT NOME, PRECO, ROUND(PRECO * 0.90, 2) AS PRECO_DESCONTO
FROM produto;

-- DATAS
SELECT ID_PEDIDO, DATA_PEDIDO, DATE(DATA_PEDIDO) AS DATAS, MONTH(DATA_PEDIDO) AS MÊS, 
YEAR(DATA_PEDIDO) AS ANO, DAY(DATA_PEDIDO) AS DIAS
FROM PEDIDO;

-- COALESCE - SUBSTITUIR A INFORMAÇÃO QUE DEIXAMOS EM NULL OU NÃO DEIXAMOS
SELECT NOME, COALESCE(TELEFONE, 'NÃO POSSUI TELEFONE') AS TELEFONE 
FROM clientes;
