-- DESAFIOS DML
-- PARTE A

-- 1. CADASTRE DOIS NOVOS CLIENTES

INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('LUISA', 'LUISA@EMAIL.COM', 19999999999, 'RIO DE JANEIRO', TRUE),
('GUSTAVO MATOS', 'GUSTAVOM@EMAIL.COM', 19999999988, 'SAO PAULO', TRUE);

-- 2.
INSERT INTO CATEGORIA (NOME) VALUES
('ESPECIAIS DA CASA');

--3.
INSERT INTO PRODUTO (NOME, PRECO, ATIVO, ID_CATEGORIA) VALUES
('AÇAI', 10.00, TRUE, 1),
('BOLO DE NUTTELA', 15.00, TRUE, 2),
('SORVETE FIT', 12.00, TRUE, 3);

--4.
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('CAROL', 'CAROL@EMAIL.COM', NULL, 'RIO DE JANEIRO', TRUE);

--5.
INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(), 'ABERTO', 100.00, 18);

--6.
INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(), 'ABERTO', 100.00, 18);
SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

-- PARTE B

--7.
UPDATE CLIENTES   
SET TELEFONE = '10846827455'
WHERE ID_CLIENTE = 2;

--8.
UPDATE CLIENTES 
SET TELEFONE = '1997777742',
    CIDADE = 'RIO DE JANEIRO'
WHERE ID_CLIENTE = 1;

--9.
UPDATE produto
SET PRECO = PRECO * 1.08
WHERE ID_CATEGORIA = 1;

