-- DESAFIOS DML
-- PARTE A

-- 1. CADASTRE DOIS NOVOS CLIENTES

INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('LUISA', 'LUISA@EMAIL.COM', 19999999999, 'RIO DE JANEIRO', TRUE),
('GUSTAVO MATOS', 'GUSTAVOM@EMAIL.COM', 19999999988, 'SAO PAULO', TRUE);

-- 2.
INSERT INTO CATEGORIA (NOME) VALUES
('ESPECIAIS DA CASA');

--3.
INSERT INTO PRODUTO (NOME, PRECO, ATIVO, ID_CATEGORIA) VALUES
('AÇAI', 10.00, TRUE, 1),
('BOLO DE NUTTELA', 15.00, TRUE, 2),
('SORVETE FIT', 12.00, TRUE, 3);

--EXEMPLO PROFESSOR
INSERT INTO PRODUTO (NOME, PRECO, ATIVO, ID_CATEGORIA) VALUES
('SORVETE FIT', 8.00, TRUE, @CATEGORIA_ESPECIAL);

--4.
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('CAROL', 'CAROL@EMAIL.COM', NULL, 'RIO DE JANEIRO', TRUE);

--5.
INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(), 'ABERTO', 100.00, 18);

--EXEMPLO PROFESSOR
SET @CLIENTE_ESPECIAL = (SELECT NOME FROM CLIENTE WHERE NOME = 'LUANA.A09@EMAIL.COM');
INSERT INTO PEDIDO (DATA_PEDIDO, STATUS, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(), 'ABERTO', 0.00, @CLIENTE_ATIVIDADE);

--6.
INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(), 'ABERTO', 100.00, 18);
SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

-- PARTE B

--7.
UPDATE CLIENTES   
SET TELEFONE = '10846827455'
WHERE ID_CLIENTE = 2;

--8.
UPDATE CLIENTES 
SET TELEFONE = '1997777742',
    CIDADE = 'RIO DE JANEIRO'
WHERE ID_CLIENTE = 1;

--9.
UPDATE produto
SET PRECO = PRECO * 1.08
WHERE ID_CATEGORIA = @CATEGORIA_ESPECIAL;

--10.

SELECT * FROM PEDIDO

UPDATE PEDIDO 
SET STATUS_PEDIDO = 'PREPARANDO'
WHERE ID_PEDIDO = @PEDIDO_ATIVIDADE;


--11.
-- SELECT SUM(QUANTIDADE*PRECO_UNITARIO) AS TOTAL
-- FROM ITEM_PEDIDO 
-- WHERE ID_PEDIDO = @CATEGORIA_ESPECIAL;

-- UPDATE PEDIDO 
-- SET VALOR_TOTAL = (SELECT SUM(QUANTIDADE*PRECO_UNITARIO) FROM ITEM_PEDIDO WHERE ID_PEDIDO=@PEDIDO_ATIVIDADE)


--12.
SELECT * FROM PRODUTO

UPDATE PRODUTO
SET ATIVO = FALSE
WHERE ID_PRODUTO = 6;

--VERSÃO PROFESSOR
SELECT * FROM PRODUTO WHERE NOME='SORVETE FIT';
UPDATE PRODUTO SET ATIVO=FALSE WHERE NOME='SORVETE FIT';
SELECT * FROM PRODUTO WHERE NOME='SORVETE FIT';


-- PARTE C

--13.
SELECT * FROM CLIENTES 

INSERT INTO CLIENTES(NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('MARIA CLARA', 'MARIAC@GMAIL.COM', '19849475825', 'CAMPINAS', TRUE)

DELETE FROM CLIENTES  
WHERE ID_CLIENTE = 16;

--VERSÃO PROFESSOR
INSERT INTO cliente (nome,email,cidade)
VALUES ('Cliente Temporário','temporario.a09@email.com','Limeira');

SELECT * FROM cliente WHERE email='temporario.a09@email.com';

DELETE FROM cliente WHERE email='temporario.a09@email.com';

SELECT * FROM cliente WHERE email='temporario.a09@email.com';

--14.
SELECT * FROM CLIENTES 

DELETE FROM CLIENTES
WHERE ID_CLIENTE = 2;

-- ERRO: AO DELETAR NÃO FOI POSSÍVEL POIS A CHAVE ESTRANGEIRA DEPENDE DE UM VÍNCULO DE RELAÇÃO COM OUTRA TABELA.
-- RESPOSTA: Cannot delete or update a parent row: a foreign key constraint fails (smartcoffee_dml_duda.pedido, CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES clientes (ID_CLIENTE))

--15.
-- RESPOSTA: POIS POSSUI DEPENDENCIAS EM OUTRA TABELA E POSSUI DADOS COM INFORMAÇÕES


--16.
INSERT INTO CATEGORIA (NOME) VALUES
('EXCLUIR DEPOIS');
DELETE FROM CATEGORIA 
WHERE NOME = 'EXCLUIR DEPOIS';