-- Active: 1788435117141@@127.0.0.1@3306@smartcoffee_dml_duda
-- BANCO DE DADOS - SMARTCOFFEE - DML 

DROP DATABASE IF EXISTS SMARTCOFFEE_DML_DUDA;

CREATE DATABASE IF NOT EXISTS SMARTCOFFEE_DML_DUDA;
USE SMARTCOFFEE_DML_DUDA;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) UNIQUE,
    TELEFONE VARCHAR(15),
    CIDADE VARCHAR(60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
    REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('ABERTO', 'PREPARANDO', 'FINALIZADO', 'CANCELADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES
    CLIENTES (ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    OBSERVACAO VARCHAR(150),
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES 
    PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES
    PRODUTO (ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO)
    REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_PAGAMENTO_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO)
    REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);

-- INSERINDO DADOS NO BD

INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('LUIS FELIPE', 'LUIS@EMAIL.COM', '1999999901', 'LIMEIRA', TRUE),
('MARIA EDUARDA', 'MARIA@EMAIL.COM', '1999999902', 'LIMEIRA', TRUE),
('MATEUS SILVA', 'MATEUS@EMAIL.COM', '1999999903', 'LIMEIRA', TRUE),
('MATHEUS ORICOLLI', 'MATHEUSC@EMAIL.COM', '1999999904', 'LIMEIRA', TRUE),
('NICOLAS FILIFE', 'NICOLAS@EMAIL.COM', '1999999905', 'LIMEIRA', TRUE),
('OTAVIO CORREIA', 'OTAVIO@EMAIL.COM', '1999999906', 'CONCHAL', TRUE),
('PEDRO MIRANDA', 'PEDRO@EMAIL.COM', '1999999907', 'LIMEIRA', TRUE),
('RAFAEL VIEIRA', 'RAFAEL@EMAIL.COM', NULL, 'LIMEIRA', TRUE),
('REBECCA HERNANDES', 'REBECCA@EMAIL.COM', NULL, 'LIMEIRA', TRUE),
('RENNAN CAMPOS', 'RENNAN@EMAIL.COM', '1999999908', 'AMERICANA', TRUE),
('SAMIRA EMILY DALOSTO', 'SAMIRA@EMAIL.COM', NULL, 'OURINHOS', FALSE),
('SOPHIA CAROLINA', 'SOPHIA@EMAIL.COM', '1999999909', 'TAUBATÉ', TRUE),
('VANESSA QUEIROZ', 'VANESSA@EMAIL.COM', '1999999910', 'LIMEIRA', TRUE),
('VINICIUS HENRIQUE', 'VINICIUS@EMAIL.COM', '1999999901', 'LIMEIRA', TRUE),
('VINICIUS OLIVEIRA', 'VINICIUSO@EMAIL.COM', '1999999901', 'CHICAGO', TRUE);

SELECT * FROM clientes;

INSERT INTO CATEGORIA (NOME) VALUES
('CAFÉ'), ('BEBIDAS QUENTES'), ('BEBIDAS GELADAS'), ('DOCES'), ('SALGADOS'), ('COMBOS');
SELECT * FROM CATEGORIA

INSERT INTO PRODUTO (NOME, PRECO, ATIVO, ID_CATEGORIA) VALUES
('CAFÉ EXPRESSO', 5.00, TRUE, 1),
('CHOCOLATE QUENTE', 8.00, TRUE, 2),
('REFRIGERANTE', 6.00, TRUE, 3),
('BOLO MATILDA', 15.00, TRUE, 4),
('MISTO QUENTE', 10.00, TRUE, 5),
('COMBO ESPECIAL', 25.50, TRUE, 6);

SELECT * FROM PRODUTO

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
('2026-08-21 08:00:00', 'FINALIZADO', 200.00, 1),
('2026-03-12 10:48:00', 'ABERTO', 50.00, 2),
('2026-07-27 07:20:00', 'CANCELADO', 87.50, 3),
('2026-10-07 08:54:00', 'PREPARANDO', 150.00, 4),
('2026-02-02 09:15:00', 'FINALIZADO', 120.00, 5),
('2026-04-02 07:30:00', 'PREPARANDO', 70.00, 6);

SELECT * FROM PEDIDO

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(13, 1, 3, 5.00, 'EXCELENTE'),
(14, 2, 4, 6.00, 'AMEI'),
(15, 3, 5, 7.00, 'MUITO BOM'),
(16, 4, 6, 8.00, 'TUDO ÓTIMO'),
(17, 5, 7, 9.00, 'EXCELENTE'),
(18, 6, 8, 10.00, 'EXCELENTE');

SELECT * FROM ITEM_PEDIDO 

INSERT INTO FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO, DESCRICAO) VALUES
(1, 'DEBITO'),
(2, 'CREDITO'),
(3, 'PIX'),
(4, 'DINHEIRO');

SELECT * FROM FORMA_PAGAMENTO


INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
(13, 2, 20.00, NOW()),
(14, 1, 60.00, NOW()),
(15, 4, 100.00, NOW() ),
(16, 2, 90.00, NOW()),
(17, 1, 48.00, NOW()),
(18, 3, 200.00, NOW());

SELECT * FROM PAGAMENTO
