-- Correcao somativa 01 - oficina mecânica
CREATE DATABASE IF NOT EXISTS OFICINA_DUDA;

USE OFICINA_DUDA;

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    TELEFONE CHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    STATUS_CLIENTE ENUM('ATIVO','INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VEICULOS (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    PLACA CHAR(8) NOT NULL UNIQUE,
    TIPO_VEICULO ENUM('CARRO', 'MOTO', 'CAMINHA') DEFAULT 'CARRO',
    COR CHAR(20),
    QUILOMETRAGEM FLOAT,
    TIPO_MOTOR ENUM ('ELETRICO', 'MANUAL'),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MARCAS (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    ANO_LACAMENTO YEAR,
    PAIS_ORIGEM VARCHAR(60),
    STATUS_MARCA ENUM ('ATIVO', 'INATIVO') DEFAULT ('ATIVO'),
    NOME_MARCA VARCHAR(30) NOT NULL,
    SITE_MARCA VARCHAR(100),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODELOS (
    ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
    COR VARCHAR(30),
    ANO_MODELO YEAR,
    VALOR_MODELO DECIMAL(10,2) NOT NULL,
    CATEGORIA ENUM ('SUV', 'HATCH', 'SEDAN', 'MOTO ESPORTIVA'),
    NOME_MODELO VARCHAR(60),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CPF_FUNCIONARIO CHAR(14) NOT NULL UNIQUE,
    STATUS_FUNCIONARIO ENUM ('ATIVO', 'INATIVO') DEFAULT ('ATIVO'),
    CARGO VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SERVICOS (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_SERVICO VARCHAR(60) NOT NULL,
    DESCRICAO_PROBLEMA VARCHAR(250) NOT NULL,
    PRECO_SERVICO DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
    DATA_INICIO DATETIME NOT NULL,
    DATA_TERMINO DATETIME NOT NULL,
    STATUS_SERVICO ENUM ('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO'),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PECAS (
    ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
    TAMANHO VARCHAR(10) NOT NULL,
    VALOR_PECA DECIMAL(10,2) NOT NULL,
    NOME_PECA VARCHAR(50) NOT NULL,
    VALIDADE DATE NOT NULL,
    STATUS_PECAS ENUM ('DISPONIVEL', 'INDISPONIVEL'),
    QTDE_PECAS INT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDEM_DE_SERVICO (
    ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
    PRIORIDADE ENUM ('URGENCIA', 'SIMPLES') NOT NULL,
    PRAZO_FINAL DATE NOT NULL,
    RANKING_ORDEM VARCHAR(40) NOT NULL,
    STATUS_SERVICO ENUM ('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO'),
    DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_CASO VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0000.00,
    FORMA_PAGAMENTO ENUM ('DEBITO', 'CREDITO', 'PIX') NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    STATUS_PAGAMENTO VARCHAR(30),
    COMPROVANTE INT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100)NOT NULL,
    CNPJ CHAR(18) NOT NULL UNIQUE,
    TELEFONE_CONTATO VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    INSCRICAO_ESTADUAL CHAR(10),
    ENDERECO_FORNECEDOR VARCHAR(100) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ALTERAÇÕES INSERINDO CAMPOS NOVOS NAS TABELAS
ALTER TABLE CLIENTES ADD IDADE INT;
ALTER TABLE FUNCIONARIOS ADD ENDERECO VARCHAR(100);
ALTER TABLE MARCAS ADD OBSERVACAO VARCHAR(255);
ALTER TABLE ORDEM_DE_SERVICO ADD AREA_SERVICO VARCHAR(60) NOT NULL;
ALTER TABLE PECAS ADD PESO FLOAT NOT NULL;
ALTER TABLE SERVICOS ADD OBSERVACAO VARCHAR(60);
ALTER TABLE VEICULOS ADD MODELO VARCHAR(60);
ALTER TABLE FORNECEDOR ADD TIPO_ENVIO VARCHAR(50);
ALTER TABLE PAGAMENTOS ADD DESCONTO DECIMAL(10,2) DEFAULT 0000.00 NOT NULL;

-- EXCLUSAO DE CAMPOS NAS TABELAS
ALTER TABLE CLIENTES DROP COLUMN IDADE;

-- RENOMEAR TABELA 
RENAME TABLE MODELOS TO MODELOS_FAB;


-- VISUALIZAR TODOS OS BD

SHOW TABLES;

-- DESCRIÇÃO SOBRE INFORMAÇÕES DA TABELA
DESCRIBE CLIENTES;