CREATE DATABASE SOMATIVA_OFICINADUDA;

USE SOMATIVA_OFICINADUDA;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE VARCHAR(20) NOT NULL,
NOME VARCHAR(50) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
DATA_DE_NASCIMENTO DATE NOT NULL,
CPF VARCHAR(15) NOT NULL UNIQUE
);
ALTER TABLE IDENTIDADE ADD EMAIL VARCHAR(30) NOT NULL;
ALTER TABLE IDENTIDADE DROP COLUMN EMAIL;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE VARCHAR(20) NOT NULL,
CPF VARCHAR(15) NOT NULL UNIQUE,
SALARIO INT NOT NULL,
NOME VARCHAR(50) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL UNIQUE
) ;
ALTER TABLE DATA_DE_NASCIMENTO ADD TELEFONE VARCHAR(20) NOT NULL;
ALTER TABLE DATA_DE_NASCIMENTO DROP COLUMN TELEFONE;

CREATE TABLE IF NOT EXISTS SERVICOS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
GARANTIA VARCHAR(20) NOT NULL,
NOME_FUNCIONARIO VARCHAR(20) NOT NULL UNIQUE,
DATA_REALIZADA DATE NOT NULL,
VALOR DECIMAL NOT NULL,
TIPO_DE_SERVICO VARCHAR(20) NOT NULL
) ;
ALTER TABLE OBSERVACOES ADD GARANTIA VARCHAR(20) NOT NULL;
ALTER TABLE OBSERVACOES DROP COLUMN GARANTIA;

CREATE TABLE IF NOT EXISTS VEICULOS (
ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR(20) NOT NULL,
MODELO VARCHAR(20) NOT NULL,
PLACA VARCHAR(10) NOT NULL UNIQUE,
MOTOR ENUM ('MANUAL', 'ELETRICO') DEFAULT 'ELETRICO',
TIPO ENUM ('CARRO', 'MOTO') DEFAULT 'CARRO'
);
ALTER TABLE VALOR ADD PLACA VARCHAR(20) NOT NULL;
ALTER TABLE VALOR DROP COLUMN PLACA;

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
VIA_PAGAMENTO VARCHAR(20) NOT NULL,
PIX VARCHAR(20) NOT NULL,
CARTAO ENUM ('DEBITO', 'CREDITO') DEFAULT 'DEBITO',
DINHEIRO VARCHAR(10) NOT NULL,
CPF_NA_NOTA VARCHAR(20) NOT NULL UNIQUE
);
ALTER TABLE COMPROVANTE ADD DINHEIRO VARCHAR(20) NOT NULL;
ALTER TABLE COMPROVANTE DROP COLUMN DINHEIRO;

CREATE TABLE IF NOT EXISTS FORNECEDORES (
ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
TELEFONE VARCHAR(20) NOT NULL,
CPF VARCHAR(20) NOT NULL UNIQUE,
ENDERECO VARCHAR(50) NOT NULL,
NOME VARCHAR(50) NOT NULL UNIQUE
);
ALTER TABLE CNPJ ADD TELEFONE VARCHAR(20) NOT NULL;
ALTER TABLE CNPJ DROP COLUMN TELEFONE;

CREATE TABLE IF NOT EXISTS ORDENS (
ID_ORDENS INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(50) NOT NULL UNIQUE,
INFORMACOES VARCHAR(100) NOT NULL,
TIPO ENUM ('LIMPEZA', 'MANUTENCAO') DEFAULT 'LIMPEZA',
TELEFONE VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE
);
ALTER TABLE NOME ADD TELEFONE VARCHAR(20) NOT NULL;
ALTER TABLE NOME DROP COLUMN TELEFONE;

CREATE TABLE IF NOT EXISTS MARCAS (
ID_MARCAS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
ANO DATE NOT NULL,
STATUS ENUM ('ATIVO', 'INATIVO'),
PAIS_ORIGEM VARCHAR(15) NOT NULL,
CATEGORIA VARCHAR(20) NOT NULL
);

ALTER TABLE TIPO ADD ANO VARCHAR(20) NOT NULL;
ALTER TABLE TIPO DROP COLUMN ANO;

CREATE TABLE IF NOT EXISTS PECAS (
ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
TIPO_PECA VARCHAR(40) NOT NULL,
TAMANHO VARCHAR(30) NOT NULL,
VALOR DECIMAL NOT NULL,
GARANTIA VARCHAR(20) NOT NULL
);

ALTER TABLE COMPROVANTE ADD VALOR VARCHAR(20) NOT NULL;
ALTER TABLE COMPROVANTE DROP COLUMN VALOR;

CREATE TABLE IF NOT EXISTS MODELOS (
ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL UNIQUE,
TELEFONE VARCHAR(20) NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL,
ANO DATE NOT NULL,
COR VARCHAR(10) NOT NULL
);
RENAME TABLE MODELOS TO modelos_fab;


